basePath: /api/v1
definitions:
  controllers.AnalyticOrderRequest:
    properties:
      apiKey:
        type: string
      dateFrom:
        type: string
      dateTo:
        type: string
    required:
    - apiKey
    - dateFrom
    - dateTo
    type: object
  controllers.ReportRequest:
    properties:
      apiKey:
        type: string
      dateFrom:
        type: string
      dateTo:
        type: string
      discount:
        type: number
      tax:
        type: number
    required:
    - apiKey
    - dateFrom
    - dateTo
    - discount
    - tax
    type: object
  services.ChartData:
    properties:
      nmID:
        type: integer
      ordersCount:
        type: integer
      ordersSumRub:
        type: integer
      prevOrdersCount:
        type: integer
      prevOrdersSumRub:
        type: integer
      vendorCode:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Report Service.
  title: API Documentation
  version: "1.0"
paths:
  /orders:
    post:
      consumes:
      - application/json
      description: Generates reports orders
      parameters:
      - description: Report request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.AnalyticOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/services.ChartData'
            type: array
        "400":
          description: Invalid request parameters or date format
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Generates reports orders
      tags:
      - orders
  /reports:
    post:
      consumes:
      - application/json
      description: Generates two Excel report files based on API key and date range,
        zips them, and returns the ZIP file for download
      parameters:
      - description: Report request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.ReportRequest'
      produces:
      - application/zip
      responses:
        "200":
          description: ZIP file containing report1.xlsx and report2.xlsx
          schema:
            type: file
        "400":
          description: Invalid request parameters or date format
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Generate and download report files
      tags:
      - reports
swagger: "2.0"
