package models

import "time"

type ReportDetails struct {
	RealizationReportID          int64     `json:"realizationreport_id"`
	DateFrom                     string    `json:"date_from"`
	DateTo                       string    `json:"date_to"`
	CreateDt                     string    `json:"create_dt"`
	CurrencyName                 string    `json:"currency_name"`
	SupplierContractCode         *string   `json:"suppliercontract_code"`
	RrdID                        int64     `json:"rrd_id"`
	GiID                         int64     `json:"gi_id"`
	DlvPrc                       float64   `json:"dlv_prc"`
	FixTariffDateFrom            string    `json:"fix_tariff_date_from"`
	FixTariffDateTo              string    `json:"fix_tariff_date_to"`
	SubjectName                  string    `json:"subject_name"`
	NmID                         int64     `json:"nm_id"`
	BrandName                    string    `json:"brand_name"`
	SaName                       string    `json:"sa_name"`
	TsName                       string    `json:"ts_name"`
	Barcode                      string    `json:"barcode"`
	DocTypeName                  string    `json:"doc_type_name"`
	Quantity                     int       `json:"quantity"`
	RetailPrice                  float64   `json:"retail_price"`
	RetailAmount                 float64   `json:"retail_amount"`
	SalePercent                  int       `json:"sale_percent"`
	CommissionPercent            float64   `json:"commission_percent"`
	OfficeName                   string    `json:"office_name"`
	SupplierOperName             string    `json:"supplier_oper_name"`
	OrderDt                      time.Time `json:"order_dt"`
	SaleDt                       time.Time `json:"sale_dt"`
	RrDt                         string    `json:"rr_dt"`
	ShkID                        int64     `json:"shk_id"`
	RetailPriceWithDiscRub       float64   `json:"retail_price_withdisc_rub"`
	DeliveryAmount               int       `json:"delivery_amount"`
	ReturnAmount                 int       `json:"return_amount"`
	DeliveryRub                  float64   `json:"delivery_rub"`
	GiBoxTypeName                string    `json:"gi_box_type_name"`
	ProductDiscountForReport     float64   `json:"product_discount_for_report"`
	SupplierPromo                float64   `json:"supplier_promo"`
	Rid                          int64     `json:"rid"`
	PpvzSppPrc                   float64   `json:"ppvz_spp_prc"`
	PpvzKvwPrcBase               float64   `json:"ppvz_kvw_prc_base"`
	PpvzKvwPrc                   float64   `json:"ppvz_kvw_prc"`
	SupRatingPrcUp               float64   `json:"sup_rating_prc_up"`
	IsKgvpV2                     float64   `json:"is_kgvp_v2"`
	PpvzSalesCommission          float64   `json:"ppvz_sales_commission"`
	PpvzForPay                   float64   `json:"ppvz_for_pay"`
	PpvzReward                   float64   `json:"ppvz_reward"`
	AcquiringFee                 float64   `json:"acquiring_fee"`
	AcquiringPercent             float64   `json:"acquiring_percent"`
	PaymentProcessing            string    `json:"payment_processing"`
	AcquiringBank                string    `json:"acquiring_bank"`
	PpvzVw                       float64   `json:"ppvz_vw"`
	PpvzVwNds                    float64   `json:"ppvz_vw_nds"`
	PpvzOfficeName               string    `json:"ppvz_office_name"`
	PpvzOfficeID                 int       `json:"ppvz_office_id"`
	PpvzSupplierID               int       `json:"ppvz_supplier_id"`
	PpvzSupplierName             string    `json:"ppvz_supplier_name"`
	PpvzInn                      string    `json:"ppvz_inn"`
	DeclarationNumber            string    `json:"declaration_number"`
	BonusTypeName                string    `json:"bonus_type_name"`
	StickerID                    string    `json:"sticker_id"`
	SiteCountry                  string    `json:"site_country"`
	SrvDbs                       bool      `json:"srv_dbs"`
	Penalty                      float64   `json:"penalty"`
	AdditionalPayment            float64   `json:"additional_payment"`
	RebillLogisticCost           float64   `json:"rebill_logistic_cost"`
	RebillLogisticOrg            string    `json:"rebill_logistic_org"`
	StorageFee                   float64   `json:"storage_fee"`
	Deduction                    float64   `json:"deduction"`
	Acceptance                   float64   `json:"acceptance"`
	AssemblyID                   int64     `json:"assembly_id"`
	Kiz                          string    `json:"kiz"`
	Srid                         string    `json:"srid"`
	ReportType                   int       `json:"report_type"`
	IsLegalEntity                bool      `json:"is_legal_entity"`
	TrbxID                       string    `json:"trbx_id"`
	InstallmentCofinancingAmount float64   `json:"installment_cofinancing_amount"`
	WibesWbDiscountPercent       int       `json:"wibes_wb_discount_percent"`
}
